### ISSUE TITLE
Allowing responsive classes for utilities other than widths?

### ISSUE THREAD

**Issue by MrDinsdale** [sky-uk/toolkit-core#109]
There have been a few occasions (especially in building Blackjack Guides) where it would have been beneficial to have responsive classes for utilities such as `u-text-right` and `u-text-center` etc.

Perhaps we could write a simple class builder loop to output `u-text-center@medium` for example. Not sure if this is a general requirement or just something that has emerged as a direct result of the guides layout.

This would get impractical for utilities such as padding and margin classes however as there would be far too many variations.

**Comment by MrDinsdale** [comment]
Something like:
```
@each $alias, $bp in $mq-breakpoints {
  $align-values: 'left', 'center', 'right', 'justify';

  @include mq($until: $bp) {
    @each $value in $align-values {
      .u-text-#{$value}\@#{$alias} {
        text-align: $value;
      }
    }
  }
}
```
Probably a little overkill but thought I'd flag it incase anyone had similar issues

**Comment by steveduffin** [comment]
I needed a similar thing with the Sky Q buy page and some storefront pages. So this would be very useful. We needed responsive classes for hiding stuff and adjusting spacing so I added classes such as .u-hide@small and .u-padding-bottom@large etc

**Comment by joebell93** [comment]
Moved to https://github.com/sky-uk/toolkit/issues/181
