### ISSUE TITLE
Update Normalize.css

### ISSUE THREAD

**Issue by csswizardry** [sky-uk/toolkit-core#126]
Normalize.css is currently at [4.2.0](https://github.com/necolas/normalize.css/releases/tag/4.2.0) but we’re running [4.0.0](https://github.com/sky-uk/toolkit-core/blob/ee6773872311dee2fe7ae119c054cb286371b984/generic/_normalize.scss). We should certainly update to the latest version somehow, which brings me on to…

Currently we just copy/paste the `.css` source into our own `.scss` version of the file. It would be nice to include Normalize.css as a dependency and then [symlink it in order to use it in our Sass](https://medium.com/@TimSeverien/symlink-is-the-answer-ab13379e342f#33d3).

**Comment by joebell93** [comment]
Does this mean users would have to manually symlink each time though? That sounds like it could be a hassle

**Comment by joebell93** [comment]
@csswizardry gave it a shot following the code from your private repo, unfortunately no luck (despite the symlink clearly working in my folder structure) 😭 

```
ERROR in /usr/local/lib/~/blackjack-toolbelt/~/css-loader!/usr/local/lib/~/blackjack-toolbelt/~/sass-loader?includePaths[]=/usr/local/lib/~/blackjack-toolbelt/node_modules&includePaths[]=/Users/jbe42/www/blackjack-toolkit/node_modules!./styles/components/blackjack-toolkit.scss
Module build failed:
@import "generic/normalize";
^
      File to import not found or unreadable: generic/normalize
Parent style sheet: /Users/jbe42/www/blackjack-toolkit/node_modules/sky-toolkit-core/_all.scss
      in /Users/jbe42/www/blackjack-toolkit/node_modules/sky-toolkit-core/_all.scss (line 97, column 1)
Error:
@import "generic/normalize";
^
      File to import not found or unreadable: generic/normalize
Parent style sheet: /Users/jbe42/www/blackjack-toolkit/node_modules/sky-toolkit-core/_all.scss
      in /Users/jbe42/www/blackjack-toolkit/node_modules/sky-toolkit-core/_all.scss (line 97, column 1)
    at options.error (/usr/local/lib/node_modules/blackjack-toolbelt/node_modules/node-sass/lib/index.js:292:26)
 @ ./styles/components/blackjack-toolkit.scss 4:14-388 13:2-17:4 14:20-394

```

**Comment by joebell93** [comment]
Moved to https://github.com/sky-uk/toolkit/issues/182
