### ISSUE TITLE
Include Supercell as a dependency(?)

### ISSUE THREAD

**Issue by csswizardry** [sky-uk/toolkit-core#127]
I extracted the layout system out of core and into its own project called [_Supercell_](https://github.com/sky-uk/supercell). This is so that we can lay out pages on non-Toolkit projects without needing to bring all of the Toolkit with it.

We can quite simply include Supercell as a dependency of core. Should we?

**Comment by joebell93** [comment]
I think so 🎉

**Comment by csswizardry** [comment]
**UPDATE:** Just thought… due to the majority of the code in this repo being my IP from long-before-Sky, we need to think about licenses etc.

**Comment by joebell93** [comment]
cc @Tom-Davidson what approach do you think we should take on this?

**Comment by Tom-Davidson** [comment]
As long as the licence is acceptable we're ok to include it. If it's @csswizardry's IP then we'll need a licence (even if it's an open source licence) to use it. Let's chat about it when you're next in the office.

**Comment by joebell93** [comment]
Moved to https://github.com/sky-uk/toolkit/issues/183
