### ISSUE TITLE
Create blank Sass template

### ISSUE THREAD

**Issue by csswizardry** [sky-uk/toolkit-core#139]
We want people to contribute new code as quickly and painlessly as possible, so let’s give them a blank Sass template that they can create new components in, on spec, and immediately.

Similar to https://raw.githubusercontent.com/inuitcss/template/master/_layer.file.scss

---
- [x] Create Template with short URL
- [x] Document in [Toolkit](https://github.com/sky-uk/toolkit)

**Comment by csswizardry** [comment]
I’m going to make a `git.io` short URL for this: what should it be?

```
http://git.io/_____
```

**Comment by joebell93** [comment]
```
http://git.io/component
```

?

**Comment by joebell93** [comment]
Added to https://github.com/sky-uk/toolkit/blob/master/CONTRIBUTING.md
