### ISSUE TITLE
[Design] Background gradient incorrect on mobile

### ISSUE THREAD

**Issue by lukecocker** [sky-uk/toolkit-core#142]
## Expected Behavior
Expecting the bg gradient to go horizontally

![image](https://cloud.githubusercontent.com/assets/19555664/19603711/f93fabf6-97a9-11e6-9cf4-f7959e64c3b3.png)

## Current Behavior
Current gradient runs vertically

![image](https://cloud.githubusercontent.com/assets/19555664/19603704/f0404222-97a9-11e6-92a1-5e32aeeeb2de.png)

**Comment by joebell93** [comment]
Fixed in https://github.com/sky-uk/toolkit-core/issues/145
