### ISSUE TITLE
Panel inner left/right innershadows

### ISSUE THREAD

**Issue by lukecocker** [sky-uk/toolkit-core#147]
## Expected Behavior
There should be an inner shadow at the top/bottom of a panel, but not the left/right

![image](https://cloud.githubusercontent.com/assets/19555664/19679989/df820070-9a9b-11e6-9b3a-f94acaa31f61.png)

## Current Behavior

Inner shadow appearing at the left/right of the panel

![image](https://cloud.githubusercontent.com/assets/19555664/19679893/93880368-9a9b-11e6-8c47-8f5e0f507922.png)

![image](https://cloud.githubusercontent.com/assets/19555664/19679948/ba189d3a-9a9b-11e6-9241-9fc80e409044.png)

**Comment by joebell93** [comment]
@lukecocker this was fixed in toolkit-ui `v0.5.1`
https://github.com/sky-uk/toolkit-ui/releases/tag/v0.5.1

Please can you confirm your devs are using the latest release?

**Comment by joebell93** [comment]
Spoke to @bradleyfowler and the devs are using `0.3.0` - this has been fixed so will close for now
