### ISSUE TITLE
[Utilities] inline-block 

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit-core#148]
## Current Behavior

In many cases (e.g. help hub pages), block text elements need to display inline.
## Possible Solution

`u-inline`, `u-text-inline` to simply set `display: inline-block;`

Thoughts?

**Comment by MrDinsdale** [comment]
Do you have any examples? Personally I think we should be careful, done this in the past and often gets messy and while there are exceptions it usually contradicts best practice.

Not sure this is something we should promote.

**Comment by joebell93** [comment]
Help Hub pages are the best example for this, but I've seen multiple examples on other projects (can't remember off the top of my head)

**Comment by joebell93** [comment]
Closing until it becomes more of an issue
