### ISSUE TITLE
Add responsive hiding classes

### ISSUE THREAD

**Issue by benjy2429** [sky-uk/toolkit-core#149]
## Expected Behavior

It might be useful to extend the `.u-hide-visually` classes with responsive modifiers.

E.g. `.u-hide-visually@small`

## Current Behavior

This is currently not possible using the toolkit, and needs custom implementations when required.

## Possible Solution

Similar to how the `.u-width` classes work.

## Context

This was required when building diagnostic flows in Sky Pages (https://github.com/sky-uk/sky-pages/pull/2139#discussion_r87177502). We needed to hide a navigation button on mobile devices, as gestures are used to navigate instead.

**Comment by joebell93** [comment]
I think this could be pretty valuable

**Comment by StefanMcCready** [comment]
I would agree, a few people have asked whether we have these or not.

**Comment by steveduffin** [comment]
I keep assuming these exist and then am filled with sadness when they don't work. 
I Volunteer as Tribute

**Comment by steveduffin** [comment]
Bashed out an idea here for discussion:
http://codepen.io/steveduffin/pen/wozXmo

**Comment by joebell93** [comment]
Closing this to move here https://github.com/sky-uk/toolkit-core/issues/109
