### ISSUE TITLE
Upgrade Stylelint

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit-core#159]
## Expected Behavior
- [x] Upgrade Stylelint version
- [x] Add/fix existing rules.

Related issues:
https://github.com/sky-uk/toolkit/issues/31

## Current Behavior
We are several versions behind on Stylelint, we should upgrade to utilise the latest features.
Current lint is also problematic, we should probably investigate a few changes.

## Attempted Fixes
About to start a new branch to investigate. 

## Context
Currently holds back Stylelint integration in Sky Pages: https://github.com/sky-uk/sky-pages/pull/2480

**Comment by joebell93** [comment]
@sky-uk/toolkit what would you guys like to see in an updated Linter?

Rules available: http://stylelint.io/user-guide/rules/
Potential plugins: http://stylelint.io/user-guide/plugins/

**Comment by steveduffin** [comment]
I wasn't able to indent this line: https://github.com/sky-uk/toolkit-ui/blob/master/components/_calendar.scss#L214 now strictly speaking all the `only screen ands` should have been on one line and so L214 would only be one indent in from `@media` but this for me highlights a general issue I have with the linting: we shouldn't be restricted when trying to make something more readable.

Another bug bear of mine is that I like my prefixes to be aligned, ala:
![screen shot 2016-12-14 at 10 12 33](https://cloud.githubusercontent.com/assets/1849493/21178097/e05473b8-c1e5-11e6-9ff2-1bcb448d7154.png)
But computer says no.

**Comment by joebell93** [comment]
@csswizardry's also found that difficult to work with:
https://github.com/sky-uk/toolkit/issues/31

**Comment by MrDinsdale** [comment]
* I really hate using values such as `0.25em`, for me `.25em` would be preferred and I know it matches better with Sky Pages.
* I also prefer single quotes.

**Comment by MrDinsdale** [comment]
@steveduffin While I personally don't do that I agree and don't think there is any reason to prevent it

**Comment by joebell93** [comment]
@MrDinsdale I have to be honest I prefer the `0.25em`, I think it's more readable. I do prefer single quotes though.

**Comment by joebell93** [comment]
@steveduffin can't for the life of me find where to fix that indentation problem for Calendar
