### ISSUE TITLE
`z-index` strategies

### ISSUE THREAD

**Issue by csswizardry** [sky-uk/toolkit-core#53]
It would be nice if we can avoid the dreaded `z-index: 99999999999999999999999999999999999999999;` problem on this project, so let’s look at either
1. [Linting for sane values](https://github.com/brigade/scss-lint/issues/460) or…
2. Managing our `z-index` values in a map or settings file.

`z-index` will likely be more problematic when we’re working with UI, because Core’s stacking will probably be pretty concrete. This raises questions of if/how do we manage `z-index` across both Core and UI, and where to we allow consumers to change or update `z-index` in their specific circumstances?

**Comment by gregorypratt** [comment]
Turning something like this into a map could be a good idea...
```
$z-over-content: 100 !default;
$z-over-control: 200 !default;
$z-over-page: 300 !default;
$z-over-screen: 400 !default;
$z-over-everything: 500 !default;
```

**Comment by joebell93** [comment]
@gregorypratt potentially, but ideally held within a sass-map too

**Comment by joebell93** [comment]
Here are all the `z-index` values being used in the Toolkit:

* -2
   * [Tile](https://github.com/sky-uk/toolkit-ui/blob/d02a33774c0f41aafbe380aaa3e8fc415109b5a1/components/_tile.scss) - caption hover state
* -1
   * [Tile](https://github.com/sky-uk/toolkit-ui/blob/d02a33774c0f41aafbe380aaa3e8fc415109b5a1/components/_tile.scss) - caption hover state
* 1
   * [Tile](https://github.com/sky-uk/toolkit-ui/blob/d02a33774c0f41aafbe380aaa3e8fc415109b5a1/components/_tile.scss) - shine
   * [Dropdown](https://github.com/sky-uk/toolkit-ui/blob/8d1daa1be9f2b1d808653e8ad20793776eb0cd26/components/_dropdown.scss) - main element
* 2
   * [Dropdown](https://github.com/sky-uk/toolkit-ui/blob/8d1daa1be9f2b1d808653e8ad20793776eb0cd26/components/_dropdown.scss) - dropdown list
* 10
   * [mixins-ui](https://github.com/sky-uk/toolkit-core/blob/4feb834650b07ca7d234df431dd9783f743a83fe/tools/_mixins-ui.scss) - panel indicator (only z-index in **toolkit-core**)
   * [Tile](https://github.com/sky-uk/toolkit-ui/blob/d02a33774c0f41aafbe380aaa3e8fc415109b5a1/components/_tile.scss) - main element
* 20
   * [Tile](https://github.com/sky-uk/toolkit-ui/blob/d02a33774c0f41aafbe380aaa3e8fc415109b5a1/components/_tile.scss) - caption + overlay
* 50
   * [Tooltip](https://github.com/sky-uk/toolkit-ui/blob/88d522eb479fd8992d00775aff69a726938dae4f/components/_tooltip.scss) - base layer
* 51
   * [Tooltip](https://github.com/sky-uk/toolkit-ui/blob/88d522eb479fd8992d00775aff69a726938dae4f/components/_tooltip.scss) - whitewash page overlay
* 52
   * [Tooltip](https://github.com/sky-uk/toolkit-ui/blob/88d522eb479fd8992d00775aff69a726938dae4f/components/_tooltip.scss) - trigger above whitewash
   * [Tooltip](https://github.com/sky-uk/toolkit-ui/blob/88d522eb479fd8992d00775aff69a726938dae4f/components/_tooltip.scss) - content bubble above whitewash
* 53
   * [Tooltip](https://github.com/sky-uk/toolkit-ui/blob/88d522eb479fd8992d00775aff69a726938dae4f/components/_tooltip.scss) - indicator layer
* 1000
   * [Spinner](https://github.com/sky-uk/toolkit-ui/blob/8d1daa1be9f2b1d808653e8ad20793776eb0cd26/components/_spinner.scss) - Overlay
   * [Shine](https://github.com/sky-uk/toolkit-ui/blob/7cd263a11474b4cce849b72ca47dc096381ad924/components/_shine.scss) - main element

**Comment by joebell93** [comment]
Moved to https://github.com/sky-uk/toolkit/issues/176
