### ISSUE TITLE
assets.sky.com prevents using fonts locally

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit-core#80]
We need to switch the `@font-face` source to `//assets.sky.com`, however, this is going to prevent any fonts from being displayed locally due to CORS restrictions.

Developers currently get around this by including [fonts.css](http://assets.sky.com/dist/1281/css/fonts.css), but I'm hesitant to start using base64 on all of our fonts.

Any idea how we could get around this?

**Comment by rosswarren** [comment]
What is the specific error you get? It has ['Access-Control-Allow-Origin'] = '*'

**Comment by joebell93** [comment]
Fixed in [v0.3.13](https://github.com/sky-uk/toolkit-core/releases/tag/v0.3.13)
